# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.14.0/deployment-apps-v1.json
apiVersion: apps/v1
kind: Deployment
metadata:
    name: "{{ .Values.appName }}"
    labels:
        app: "{{ .Values.appName }}"
spec:
    #replicas: {{ .Values.replicas }}
    selector:
        matchLabels:
            app: "{{ .Values.appName }}"
            tier: frontend
    template:
        metadata:
            labels:
                app: "{{ .Values.appName }}"
                tier: frontend
        spec: # Pod spec
            containers:
                - name: mycontainer
                  image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
                  ports:
                      - containerPort: 80
                  resources:
                      requests:
                          memory: "16Mi"
                          cpu: "50m" # 500milliCPUs (1/2 CPU)
                      limits:
                          memory: "128Mi"
                          cpu: "100m"
